import type { Metadata } from "next";
import "./globals.css";
import {inter} from "@/app/fonts/fonts";
import {Navbar} from "@/components/ui/nav";
import ReactQueryProvider from "@/lib/providers/ReactQueryProviders";
import {auth} from "@/auth.config";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface rootLayoutProps{
    children:React.ReactNode,
    modal:React.ReactNode
}



export default async function RootLayout({
  children,modal
}:rootLayoutProps) {

    const user = await auth()


    return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >

      <div className={" bg-gradient-to-r from-purple-800 to-purple-950 h-full flex flex-col gap-5"}>

          <ReactQueryProvider>
              <Navbar user={user}></Navbar>
              {modal}
              {children}
          </ReactQueryProvider>



      </div>
      </body>
    </html>
  );
}
